### ISSUE TITLE
Contour Line Planner

### ISSUE THREAD

**Issue by denesh-globotix** [ipa320/ipa_coverage_planning#11]
While taking a look at the explanation in the ros wiki: http://wiki.ros.org/ipa_room_exploration it was impressive to see the contour line planner. Do you have a guide as to how to go about planning such a path? I notice that there are 8 options, would it be possible to point towards the algorithm that produces the paths that are contour like? 

	if (room_exploration_algorithm_ == 1)
		ROS_INFO("You have chosen the grid exploration method.");
	else if(room_exploration_algorithm_ == 2)
		ROS_INFO("You have chosen the boustrophedon exploration method.");
	else if(room_exploration_algorithm_ == 3)
		ROS_INFO("You have chosen the neural network exploration method.");
	else if(room_exploration_algorithm_ == 4)
		ROS_INFO("You have chosen the convexSPP exploration method.");
	else if(room_exploration_algorithm_ == 5)
		ROS_INFO("You have chosen the flow network exploration method.");
	else if(room_exploration_algorithm_ == 6)
		ROS_INFO("You have chosen the energy functional exploration method.");
	else if(room_exploration_algorithm_ == 7)
		ROS_INFO("You have chosen the voronoi exploration method.");
	else if(room_exploration_algorithm_ == 8)
		ROS_INFO("You have chosen the boustrophedon variant exploration method.");

**Comment by ipa-rmb** [comment]
I guess it should be the Voronoi exploration method, but I am not 100% sure anymore. Please try that one, it is at least the most fitting in my eyes.

**Comment by denesh-globotix** [comment]
Hi @ipa-rmb, the Voronoi exploration method seems to do the trick, it traces the outer region of a map before moving inwards. A rough image can be seen below: 

![image](https://user-images.githubusercontent.com/87276217/140450545-2d30980c-07ad-4e17-8b00-8622a07c96fe.png)

Which is similar to the contour line planning shown in this [link](http://wiki.ros.org/ipa_room_exploration): 
![image](https://user-images.githubusercontent.com/87276217/140470239-618bed93-ac49-4773-b509-080ca98a7e67.png)


Will be closing the issue for the time being since all is good
