### ISSUE TITLE
How to integrate this algorithm into move_base?

### ISSUE THREAD

**Issue by genius-hl** [ipa320/ipa_coverage_planning#19]
Dear author, thanks for your work!  Can this algorithm be integrated into ros move_base as a global path planner?

**Comment by jlee-67** [comment]
I would like to know this too.

**Comment by genius-hl** [comment]
> I would like to know this too.

Hey,  Have you successfully compiled this package stack ? I need to download many dependecies or other packages to solve the error when complied the package over and over. The error like this:
Could not find a package configuration file provided by "***"
but I think this is not a good solution.
If you have good suggestions, please tell me, thanks!

**Comment by ipa-foj** [comment]
Thank you for your interest in the software. We do not plan to include it into move_base as a standard package, as it is a very specific module only needed for special robotic applications. 

Regarding the many packages to download: Unfortunately there are many dependencies that need to be downloaded, right now we don't see that it can be made much easier, sorry for that..
