### ISSUE TITLE
I have a big problem, can you help me solve it?

### ISSUE THREAD

**Issue by weicyingqiaopian** [ipa320/ipa_coverage_planning#33]
[ WARN] [1715306051.567011275]: Transitioning goal to LOST
Got a path with 0 nodes.
OpenCV Error: Assertion failed (size.width>0 && size.height>0) in imshow, file /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/highgui/src/window.cpp, line 304
terminate called after throwing an instance of 'cv::Exception'
  what():  /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/highgui/src/window.cpp:304: error: (-215) size.width>0 && size.height>0 in function imshow

[room_exploration/room_exploration_client-1] process has died [pid 68017, exit code -6, cmd /home/ros1ubuntu/catkin_ws/devel/lib/ipa_room_exploration/room_exploration_client __name:=room_exploration_client __log:=/home/ros1ubuntu/.ros/log/6fb2da8c-0cdd-11ef-be0a-000c29135610/room_exploration-room_exploration_client-1.log].
log file: /home/ros1ubuntu/.ros/log/6fb2da8c-0cdd-11ef-be0a-000c29135610/room_exploration-room_exploration_client-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by hcws** [comment]
I have the same problem,can you tell how to solve it.
