### ISSUE TITLE
When I use this ipa_building_navigation start the server and the client nothing happens, is there a sample client to look at?

### ISSUE THREAD

**Issue by weicyingqiaopian** [ipa320/ipa_coverage_planning#34]
![image](https://github.com/ipa320/ipa_coverage_planning/assets/150759172/409d4501-ba6d-40e6-8dbb-38126e496084)
![image](https://github.com/ipa320/ipa_coverage_planning/assets/150759172/c4ed1683-e120-49b8-996a-4ef7310bd917)
I'm anxious about this problem, my friend, please help me solve this problem

**Comment by ipa-rmb** [comment]
Use rostopic list to seek whether all topic names fit. Usually they do, but depending on your environment this might be different. E.g. is the action /room_segmentation/room_segmentation_server available from the topic list?

**Comment by weicyingqiaopian** [comment]
ros1ubuntu@ubuntu:~$ rostopic list 
/room_segmentation/room_segmentation_server/cancel
/room_segmentation/room_segmentation_server/feedback
/room_segmentation/room_segmentation_server/goal
/room_segmentation/room_segmentation_server/result
/room_segmentation/room_segmentation_server/status
/room_sequence_planning/room_sequence_planning_server/cancel
/room_sequence_planning/room_sequence_planning_server/feedback
/room_sequence_planning/room_sequence_planning_server/goal
/room_sequence_planning/room_sequence_planning_server/parameter_descriptions
/room_sequence_planning/room_sequence_planning_server/parameter_updates
/room_sequence_planning/room_sequence_planning_server/result
/room_sequence_planning/room_sequence_planning_server/room_sequence_marker
/room_sequence_planning/room_sequence_planning_server/status
/rosout
/rosout_agg
ros1ubuntu@ubu

**Comment by ipa-rmb** [comment]
Ok, all topics are present with correct name. The client should be able to connect. @ipa-foj any ideas from your side?

**Comment by weicyingqiaopian** [comment]
Thank you for your answer, I didn't start navigating when I used the navigation, is there a client that can be used

**Comment by ipa-rmb** [comment]
Yes, if this is not enabled, the robot won't move: https://github.com/ipa320/ipa_coverage_planning/blob/f8a1dae4a09693f36a84fd92b6f9772d4c6faff1/ipa_room_exploration/ros/launch/room_exploration_action_server_params.yaml#L34

You will just receive the planned robot path as the response. 

BTW, I am writing this the third time in a third issue of you. Can you please consolidate your issues as it seems you are not having multiple problems.

**Comment by weicyingqiaopian** [comment]
Ok, thanks I bothered you, I've changed it to true
![Uploading 微信截图_20240515161923.png…]()

**Comment by ipa-foj** [comment]
As it seems this issue is the same as the open one #32, can this issue be closed?

**Comment by weicyingqiaopian** [comment]
thanks
