### ISSUE TITLE
When I found out that there was a coverage path plan on the map, but the robot did not follow the path plan

### ISSUE THREAD

**Issue by weicyingqiaopian** [ipa320/ipa_coverage_planning#36]
![image](https://github.com/ipa320/ipa_coverage_planning/assets/150759172/380eded3-ac25-4e8a-9853-e08d54e331ef)

**Comment by ipa-rmb** [comment]
Please provide a useful problem description, otherwise it is impossible for us to provide hints. In your picture, the robot is only roughly localized. Did localization stabilize afterwards?

**Comment by weicyingqiaopian** [comment]
Thank you for your answer, after I positioned it, the robot did not execute according to the algorithm plan

**Comment by ipa-rmb** [comment]
Did you enable path execution with the software? https://github.com/ipa320/ipa_coverage_planning/blob/f8a1dae4a09693f36a84fd92b6f9772d4c6faff1/ipa_room_exploration/ros/launch/room_exploration_action_server_params.yaml#L34

**Comment by weicyingqiaopian** [comment]
There is no change even if it is changed to true
